# Page settings
baseurl = "http://dunritegames.gg"
title = "Dun Rite Games"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/style5.css", "css/custom.css"]

  # Meta
  author = "felipe.torres@elitesports.mx"
  description = ""
  email = "info@elitesports.mx"
  # Navigation
  [params.navigation]
    brand = "Dun Rite Games"
    home = "Home"
    work = "Workplace"
    testimonials = "Testimonials"
    services = "Studio Perks"
    about = "Team"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "Dun Rite Games"
    subtitle = 'Spelled wrong, but <span style="color: #9900ff; font-weight: bold">Done Right!</span>'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

    # mission = "Tired of waiting for mobile games that rival the blockbusters from game consoles? Fret no more, Dun Rite Games has arrived. Created by gamers for gamers!"
    mission = "We want to make games that tell in depth stories, driven by gameplay, that everybody can enjoy."

  # [[params.intro.item]]
  #   title = "Plan"
  #   description = "To develop games 'done right', ."
  #   url = "#"
  #   button = "Get In Touch"
  #   icon = "icon-bulb"
  #   img = "img_7.jpg"

  # [[params.intro.item]]
  #   title = "Develop"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   url = "#"
  #   button = "Click Me"
  #   icon = "icon-wrench"
  #   img = "img_8.jpg"

  # [[params.intro.item]]
  #   title = "Launch"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   url = "#"
  #   button = "Why us?"
  #   icon = "icon-rocket"
  #   img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Workplace"
    description = "We want nothing to stand on the way of creativity and quality and so, we strive to provide a stress-free environment where people can have fun while working, or working while having fun."
    footertext = ''

    [[params.work.row]]
      img = "Workplace1.jpeg"
      alt = "Workplace1"
      title = "Sit-To-Stand Desks"
      subtitle = "To work standing or sitting"

    [[params.work.row]]
      img = "Workplace2.jpeg"
      alt = "Workplace2"
      title = "Cutting-edge equipment"
      subtitle = "Devices and software licenses"

    [[params.work.row]]
      img = "Workplace3.jpeg"
      alt = "Workplace3"
      title = "Gaming station"
      subtitle = "Stress-relieving, rivalry-inducing"

    [[params.work.row]]
      img = "Workplace4.jpeg"
      alt = "Workplace4"
      title = "Paid gym subscription"
      subtitle = "To a local, fully-equiped Gym"

    [[params.work.row]]
      img = "Workplace5.jpeg"
      alt = "Beverages"
      title = "Endless refreshments"
      subtitle = "Don't forget to stay hydrated!"

    [[params.work.row]]
      img = "Workplace6.jpeg"
      alt = "Beach"
      title = "Close to world-famous beaches"
      subtitle = "It's what Cancun is known for, after all"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"




  # Services section
  [params.services]
    enable = true
    title = "Studio Perks"
    description = "We spoil our people, so they don't want to leave us. Ever :)"

    [[params.services.item]]
      title = "Fun work environment"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-game-controller"
    
    [[params.services.item]]
      title = "Learning resources"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-graduation"

    [[params.services.item]]
      title = "Flexible working hours"
      description = "We believe people"
      icon = "icon-hourglass"

    [[params.services.item]]
      title = "Attractive salaries"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-wallet"

    [[params.services.item]]
      title = "Gym membership"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-trophy"

    [[params.services.item]]
      title = "Free snacks and beverages"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-cup"

    [[params.services.item]]
      title = "Maternity leave"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-user-female"

    [[params.services.item]]
      title = "Relocation support"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-plane"

  # About section
  [params.about]
    enable = true
    title = "Team"
    description = "We are proud of the uniqueness of each person in our studio. And so, we look for highly independent and motivated people that love to create."

    [[params.about.item]]
      name = "Jake Dobbins"
      position = "Founder"
      description = "If you want something 'Dun Rite', do it yourself!"
      img = "Jake.jpg"
      alt = "Jake"
      social = [
        ["icon-twitter", "https://twitter.com/onehiveraids?lang=en"],
        ["icon-youtube", "https://www.youtube.com/user/OneHiveRaids"],
        ["icon-twitch", "https://www.twitch.tv/onehiveraids"],
        ["icon-linkedin", "https://www.linkedin.com/in/jake-dobbins-85babb152/"]
      ]

    [[params.about.item]]
      name = "Ricardo Velez"
      position = "Founder"
      description = "Problem solver, curious engineer, dreaming up the future!"
      img = "Ricardo.jpg"
      alt = "Ricardo"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/ironbato/"],
        ["icon-twitter", "https://twitter.com/iron_bato?lang=en"],
        ["icon-globe", "http://ironbato.com"]
      ]

    [[params.about.item]]
      name = "Manuel Otheo"
      position = "Technical Director"
      description = "Be hungry, be humble and always trust the process."
      img = "Manuel.jpg"
      alt = "Manuel Otheo"
      social = [
        ["icon-globe", "http://manuelotheo.com"],
        ["icon-twitter", "https://twitter.com/lootheo"],
        ["icon-linkedin", "https://www.linkedin.com/in/manuelotheo/"],
        ["icon-github", "https://github.com/Lootheo"]
      ]

    [[params.about.item]]
      name = "Angel Revuelta"
      position = "Art Director "
      description = "Oh no, this is awkward."
      img = "Angel.jpg"
      alt = "Angel Revuelta"
      social = [
        ["icon-instagram", "https://www.instagram.com/angelrevbla/"],
        ["icon-linkedin", "https://www.linkedin.com/in/angel-revuelta-32aaa869/"]
      ]

    [[params.about.item]]
      name = "Jocelyn Castro"
      position = "Animation and Copositing Artist"
      description = "To build worlds that cut across platforms, and bring people together."
      img = "Jocelyn.jpg"
      alt = "Jocelyn Castro"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/jocelyn-castro-mercado-274955112/"]
      ]

    [[params.about.item]]
      name = "Felipe Perugachi"
      position = "Gameplay Developer"
      description = "Give me foods and I'll make games."
      img = "Felipe.jpg"
      alt = "Felipe Perugachi"
      social = [
        ["icon-globe", "https://felipe-torres.github.io"],
        ["icon-linkedin", "https://www.linkedin.com/in/lfelipetorres/"],
        ["icon-twitter", "https://twitter.com/xipeluife"],
        ["icon-instagram", "https://www.instagram.com/felipe.perugachi/"],
        ["icon-github", "https://github.com/felipe-torres"]
      ]

    [[params.about.item]]
      name = "Raúl Báez"
      position = "Backend Engineer"
      description = "Always passionate of new technologies and always willing to learn more."
      img = "Raul.jpg"
      alt = "Raul Baez"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/raul-alejandro-baez-camarillo-b9970052/"]
      ]

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = "Contact"
    title = "Get in touch"
    description = "Would you like to reach us? Send us a message, we don't bite!"

    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Cancún, Mexico"],
        ["icon-phone", "(+52) 998-310-2401"],
        ["icon-envelope", "info@elitesports.mx"],
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; 2018 Dun Rite Games. Elate theme Free HTML5. All Rights Reserved.'
    links = [
        ["icon-twitter", "https://twitter.com/dunritegames"],
        ["icon-facebook", "https://www.facebook.com/dunritegames/"],
        ["icon-linkedin", "https://www.linkedin.com/company/dunritegames/"]
      ]
